
(()=>{
const c=document.getElementById('game'),ctx=c.getContext('2d',{alpha:false}),mini=document.getElementById('minimap'),mctx=mini.getContext('2d');
const menu=document.getElementById('menu'),hud=document.getElementById('hud'),heroesEl=document.getElementById('heroes'),shop=document.getElementById('shop');
const conn=document.getElementById('conn'),online=document.getElementById('online'),hname=document.getElementById('hname'),lv=document.getElementById('lv'),gold=document.getElementById('gold'),xp=document.getElementById('xp'),pts=document.getElementById('pts'),hp=document.getElementById('hp'),mp=document.getElementById('mp'),feed=document.getElementById('feed'),waveEl=document.getElementById('wave'),kdEl=document.getElementById('kd');
const WORLD=4000;
const heroes={guardian:['🛡️','Guardian','Tank'],arcanist:['🔮','Arcanist','Mage'],ranger:['🏹','Ranger','Carry'],assassin:['🗡️','Assassin','Assassin'],druid:['🌿','Druid','Support'],berserker:['⚔️','Berserker','Fighter']};
const lanePts={top:[[440,3560],[410,3100],[460,2600],[560,2100],[700,1600],[950,1150],[1350,800],[2000,560],[2750,440],[3560,440]],mid:[[450,3550],[950,3100],[1450,2550],[2000,2000],[2550,1450],[3100,950],[3550,440]],bot:[[440,3560],[950,3600],[1500,3580],[2100,3500],[2650,3250],[3050,2850],[3320,2300],[3480,1600],[3560,440]]};
const camps={large:[[1150,1450],[2550,2950]],small:[[1450,1050],[2900,3250]],ancient:[[1650,2350],[2350,1650]],rune:[[2000,1150],[2000,2850]]};
let selected='guardian',ws=null,meId=null,state={players:{},minions:{},towers:{},camps:{},bosses:{},buildings:[],online:0,wave:0},render={players:{},minions:{}};
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2),cam={x:2000,y:2000,z:1};let last=performance.now(),waterT=0;let moveTarget=null,keys=new Set(),particles=[],sparks=[],mobile=matchMedia('(pointer:coarse)').matches,joyId=null,lastMoveSend=0,kills=0,deaths=0;
for(const [k,v] of Object.entries(heroes)){const b=document.createElement('button');b.className='hero'+(k===selected?' sel':'');b.innerHTML=`<div class="ico">${v[0]}</div><b>${v[1]}</b><small>${v[2]}</small>`;b.onclick=()=>{selected=k;document.querySelectorAll('.hero').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')};heroesEl.appendChild(b)}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const MAP_CANVAS=document.createElement('canvas');MAP_CANVAS.width=1600;MAP_CANVAS.height=1600;const MAP_CTX=MAP_CANVAS.getContext('2d',{alpha:false});
function buildStaticMap(){const g=MAP_CTX.createLinearGradient(0,0,0,1600);g.addColorStop(0,'#587747');g.addColorStop(1,'#405f38');MAP_CTX.fillStyle=g;MAP_CTX.fillRect(0,0,1600,1600);const s=1600/WORLD;MAP_CTX.save();MAP_CTX.scale(s,s);for(let i=0;i<900;i++){const x=(i*97)%WORLD,y=(i*193)%WORLD;MAP_CTX.fillStyle=i%3===0?'rgba(255,240,180,.06)':'rgba(15,45,20,.055)';MAP_CTX.fillRect(x,y,10+(i%4)*6,7+(i%3)*5)}
function path(points,w,col){MAP_CTX.strokeStyle=col;MAP_CTX.lineWidth=w;MAP_CTX.lineCap='round';MAP_CTX.lineJoin='round';MAP_CTX.beginPath();points.forEach((q,i)=>i?MAP_CTX.lineTo(q[0],q[1]):MAP_CTX.moveTo(q[0],q[1]));MAP_CTX.stroke()}
for(const l of ['top','mid','bot']){path(lanePts[l],108,'#2e271e');path(lanePts[l],78,'#6d5639');path(lanePts[l],44,'#98734a')}
MAP_CTX.strokeStyle='#226d80';MAP_CTX.lineWidth=230;MAP_CTX.lineCap='round';MAP_CTX.beginPath();MAP_CTX.moveTo(150,3900);MAP_CTX.bezierCurveTo(850,3250,1800,2450,2500,1500);MAP_CTX.bezierCurveTo(3000,850,3450,400,3900,120);MAP_CTX.stroke();MAP_CTX.strokeStyle='#4eabbc';MAP_CTX.lineWidth=170;MAP_CTX.stroke();
MAP_CTX.strokeStyle='#99a875';MAP_CTX.lineWidth=16;MAP_CTX.beginPath();MAP_CTX.moveTo(155,3780);MAP_CTX.bezierCurveTo(860,3140,1810,2360,2510,1410);MAP_CTX.bezierCurveTo(3010,780,3450,330,3880,90);MAP_CTX.stroke();
function staticTree(x,y,scale=1){MAP_CTX.fillStyle='#513a24';MAP_CTX.fillRect(x-6*scale,y+6*scale,12*scale,24*scale);MAP_CTX.fillStyle='#173c22';MAP_CTX.beginPath();MAP_CTX.arc(x,y,34*scale,0,Math.PI*2);MAP_CTX.fill();MAP_CTX.fillStyle='#2d6a36';MAP_CTX.beginPath();MAP_CTX.arc(x-18*scale,y-12*scale,23*scale,0,Math.PI*2);MAP_CTX.fill();MAP_CTX.fillStyle='#4b8d45';MAP_CTX.beginPath();MAP_CTX.arc(x+14*scale,y-15*scale,21*scale,0,Math.PI*2);MAP_CTX.fill()}
const zones=[[850,1250],[1200,900],[2900,1050],[3150,1400],[900,2850],[1250,3180],[2700,3050],[3000,2750],[600,2100],[3400,1950]];for(const [zx,zy] of zones){for(let i=0;i<13;i++){const a=i*.92,r=70+(i%5)*55;staticTree(zx+Math.cos(a)*r,zy+Math.sin(a)*r*.75,.72+(i%3)*.16)}}
for(const [x,y] of [[2000,1500],[2000,2500]]){MAP_CTX.fillStyle='#8c7251';MAP_CTX.fillRect(x-100,y-34,200,68);MAP_CTX.fillStyle='#b59b72';for(let i=-80;i<=80;i+=40)MAP_CTX.fillRect(x+i,y-32,24,64)}
MAP_CTX.restore()}
buildStaticMap();
function sx(x){return(x-cam.x)*cam.z+W/2}function sy(y){return(y-cam.y)*cam.z+H/2}function wsurl(){return(location.protocol==='https:'?'wss://':'ws://')+location.host}
function send(o){if(ws?.readyState===1)ws.send(JSON.stringify(o))}
function connect(){conn.textContent='CONNECTING…';conn.className='pill bad';ws=new WebSocket(wsurl());ws.onopen=()=>{conn.textContent='ONLINE';conn.className='pill good';send({type:'join',name:document.getElementById('nick').value||'Player',hero:selected})};ws.onclose=()=>{conn.textContent='OFFLINE — reconnecting';conn.className='pill bad';setTimeout(connect,1200)};ws.onmessage=e=>{const p=JSON.parse(e.data);if(p.type==='welcome')meId=p.id;if(p.type==='state'){state=p;online.textContent='ONLINE '+p.online;waveEl.textContent=p.wave;syncRender()}}}
function syncRender(){for(const [id,p] of Object.entries(state.players)){let r=render.players[id];if(!r)render.players[id]={...p,tx:p.x,ty:p.y,x:p.x,y:p.y};else{const old=r.attackCd;Object.assign(r,{tx:p.x,ty:p.y,hp:p.hp,maxHp:p.maxHp,mana:p.mana,maxMana:p.maxMana,level:p.level,gold:p.gold,xp:p.xp,skillPoints:p.skillPoints,skill:p.skill,dead:p.dead,team:p.team,name:p.name,hero:p.hero,dir:p.dir,attackCd:p.attackCd,cd:p.cd,inventory:p.inventory,items:p.items});if(old!==undefined&&p.attackCd>old+100){addFX(p.x,p.y,'hit',p.team)}}}for(const id in render.players)if(!state.players[id])delete render.players[id];for(const [id,m] of Object.entries(state.minions)){let r=render.minions[id];if(!r)render.minions[id]={...m,tx:m.x,ty:m.y,x:m.x,y:m.y};else Object.assign(r,{tx:m.x,ty:m.y,hp:m.hp,maxHp:m.maxHp,team:m.team,lane:m.lane,type:m.type});}for(const id in render.minions)if(!state.minions[id])delete render.minions[id]}
function addFX(x,y,type='hit',team='blue'){const limit=60;if(particles.length>limit)particles.splice(0,10);const n=type==='spell'?7:type==='hit'?4:5;for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(type==='spell'?80:45)+Math.random()*55;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.26+.3*Math.random(),max:.56,size:1.6+Math.random()*3.6,type,team})}}
function drawParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;const a=p.life/p.max;ctx.globalAlpha=a;ctx.fillStyle=p.team==='blue'?'#71bbff':p.team==='red'?'#ff788b':'#ffe089';ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),p.size*cam.z,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawGround(){ctx.save();ctx.translate(W/2,H/2);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);ctx.drawImage(MAP_CANVAS,0,0,WORLD,WORLD);ctx.restore()}
function drawMapStatic(){drawGround()}
function drawResourceCamps(){for(const [kind,list] of Object.entries(camps)){for(const [x,y] of list){const c=Object.values(state.camps).find(v=>Math.abs(v.x-x)<2&&Math.abs(v.y-y)<2);const X=sx(x),Y=sy(y),ss=cam.z;if(kind==='rune'){ctx.globalAlpha=c?.alive===false?.22:.95;ctx.fillStyle='#4fe7ff';ctx.beginPath();ctx.moveTo(X,Y-15*ss);ctx.lineTo(X+11*ss,Y);ctx.lineTo(X,Y+15*ss);ctx.lineTo(X-11*ss,Y);ctx.closePath();ctx.fill();ctx.globalAlpha=1}else{const col=kind==='ancient'?'#6d7079':kind==='large'?'#775842':'#8f6d50';ctx.fillStyle=col;ctx.beginPath();ctx.arc(X,Y,18*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle=kind==='ancient'?'#b9c0c9':'#d29b72';ctx.beginPath();ctx.arc(X-6*ss,Y-6*ss,7*ss,0,Math.PI*2);ctx.fill();drawHP(X-24*ss,Y+20*ss,48*ss,5,c?.hp||0,c?.maxHp||1,'#88d87a')}}}} 
function drawBuildings(){for(const b of (state.buildings||[])){const X=sx(b.x),Y=sy(b.y),ss=cam.z;ctx.save();if(b.kind==='shop'){ctx.fillStyle='#8a6745';ctx.fillRect(X-24*ss,Y-18*ss,48*ss,36*ss);ctx.fillStyle='#e0b05a';ctx.beginPath();ctx.moveTo(X-30*ss,Y-18*ss);ctx.lineTo(X,Y-36*ss);ctx.lineTo(X+30*ss,Y-18*ss);ctx.closePath();ctx.fill();ctx.fillStyle='#4e3726';ctx.fillRect(X-7*ss,Y,14*ss,18*ss)}else if(b.kind==='fountain'){ctx.fillStyle=b.team==='blue'?'#57b6ff':'#ff697f';ctx.beginPath();ctx.arc(X,Y,26*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9f9ff';ctx.beginPath();ctx.arc(X,Y-8*ss,10*ss,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#6e746e';ctx.fillRect(X-17*ss,Y-24*ss,34*ss,48*ss);ctx.fillStyle='#b9a16d';ctx.beginPath();ctx.moveTo(X-22*ss,Y-24*ss);ctx.lineTo(X,Y-42*ss);ctx.lineTo(X+22*ss,Y-24*ss);ctx.closePath();ctx.fill()}ctx.restore()}}
function drawBosses(){for(const b of Object.values(state.bosses||{})){const X=sx(b.x),Y=sy(b.y),ss=cam.z;if(!b.alive){ctx.globalAlpha=.18;ctx.fillStyle='#7f8b8c';ctx.beginPath();ctx.arc(X,Y,30*ss,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;continue}ctx.save();ctx.fillStyle='#18141d';ctx.beginPath();ctx.ellipse(X,Y+10*ss,34*ss,15*ss,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#54545e';ctx.beginPath();ctx.ellipse(X,Y,27*ss,31*ss,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a9b4c2';ctx.beginPath();ctx.arc(X,Y-20*ss,15*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffbd4a';ctx.beginPath();ctx.arc(X-6*ss,Y-22*ss,3*ss,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(X+6*ss,Y-22*ss,3*ss,0,Math.PI*2);ctx.fill();drawHP(X-40*ss,Y-56*ss,80*ss,6,b.hp,b.maxHp,'#ffb84a');ctx.fillStyle='#ffe8ad';ctx.textAlign='center';ctx.font=`900 ${Math.max(9,12*ss)}px Inter,Arial`;ctx.fillText(b.name,X,Y-66*ss);ctx.restore()}}
function drawBases(){for(const [team,x,y] of [['blue',330,3660],['red',3670,340]]){const X=sx(x),Y=sy(y),ss=cam.z,col=team==='blue'?'#58b4ff':'#ff6179';ctx.save();ctx.fillStyle=team==='blue'?'#123047':'#401827';ctx.beginPath();ctx.arc(X,Y,125*ss,0,Math.PI*2);ctx.fill();ctx.strokeStyle=col;ctx.lineWidth=5*ss;ctx.stroke();ctx.fillStyle='#dce6eb';ctx.beginPath();ctx.moveTo(X,Y-70*ss);ctx.lineTo(X-62*ss,Y+35*ss);ctx.lineTo(X+62*ss,Y+35*ss);ctx.closePath();ctx.fill();ctx.fillStyle=col;ctx.fillRect(X-42*ss,Y+12*ss,84*ss,10*ss);ctx.restore()}}function drawTowers(){for(const t of Object.values(state.towers)){if(t.hp<=0)continue;const X=sx(t.x),Y=sy(t.y),s=cam.z,col=t.team==='blue'?'#60bbff':'#ff6c82';ctx.save();ctx.globalAlpha=.22;ctx.fillStyle=col;ctx.beginPath();ctx.arc(X,Y,38*s,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#b8c6ca';ctx.beginPath();ctx.moveTo(X-12*s,Y+28*s);ctx.lineTo(X-15*s,Y-22*s);ctx.lineTo(X,Y-36*s);ctx.lineTo(X+15*s,Y-22*s);ctx.lineTo(X+12*s,Y+28*s);ctx.closePath();ctx.fill();ctx.fillStyle=col;ctx.fillRect(X-19*s,Y-42*s,38*s,7*s);drawHP(X-38*s,Y-52*s,76*s,6,t.hp,t.maxHp,col);ctx.restore()}}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath()}function drawHP(x,y,w,h,v,m,col){ctx.fillStyle='#06100ddd';rounded(x,y,w,h,h/2);ctx.fill();ctx.fillStyle=col;rounded(x+1,y+1,Math.max(0,(w-2)*v/m),h-2,(h-2)/2);ctx.fill()}
function drawHero(p,isMe=false){if(p.dead)return;const X=sx(p.x),Y=sy(p.y),ss=cam.z,col=p.team==='blue'?'#55adff':'#ff667c';ctx.save();ctx.translate(X,Y);ctx.rotate(p.dir||0);ctx.globalAlpha=.18;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(0,18*ss,25*ss,10*ss,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(0,5*ss,22*ss,18*ss,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9e3e8';ctx.beginPath();ctx.arc(0,-10*ss,12*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle='#283d47';ctx.fillRect(-13*ss,-3*ss,26*ss,6*ss);if(p.hero==='guardian'||p.hero==='berserker'){ctx.fillStyle='#e2c07b';ctx.fillRect(13*ss,-5*ss,18*ss,6*ss);ctx.fillStyle='#8c6236';ctx.fillRect(23*ss,-9*ss,10*ss,14*ss)}else if(p.hero==='ranger'){ctx.strokeStyle='#e5a86c';ctx.lineWidth=3*ss;ctx.beginPath();ctx.arc(18*ss,-2*ss,11*ss,-1.1,1.1);ctx.stroke();ctx.beginPath();ctx.moveTo(18*ss,-13*ss);ctx.lineTo(18*ss,9*ss);ctx.stroke()}else if(p.hero==='assassin'){ctx.fillStyle='#9a6cff';ctx.beginPath();ctx.moveTo(17*ss,0);ctx.lineTo(35*ss,-9*ss);ctx.lineTo(35*ss,9*ss);ctx.closePath();ctx.fill()}else if(p.hero==='arcanist'){ctx.fillStyle='#b17cff';ctx.beginPath();ctx.arc(17*ss,-4*ss,7*ss,0,Math.PI*2);ctx.fill()}else if(p.hero==='druid'){ctx.strokeStyle='#7bea9b';ctx.lineWidth=4*ss;ctx.beginPath();ctx.moveTo(12*ss,4*ss);ctx.lineTo(27*ss,-12*ss);ctx.stroke()}ctx.restore();drawHP(X-30*ss,Y-44*ss,60*ss,7,p.hp,p.maxHp,col);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`800 ${Math.max(9,11*ss)}px Inter,Arial`;ctx.fillText((isMe?'★ ':'')+p.name,X,Y-52*ss)}
function drawMinion(m){if(!m||m.hp<=0)return;const X=sx(m.x),Y=sy(m.y),ss=cam.z*(m.type==='siege'?1.15:.92),col=m.team==='blue'?'#5aaeff':'#ff6a7f';ctx.save();ctx.translate(X,Y);ctx.globalAlpha=.16;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(0,9*ss,13*ss,6*ss,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(m.type==='siege'){ctx.fillStyle='#49515a';ctx.fillRect(-17*ss,-10*ss,34*ss,22*ss);ctx.fillStyle=col;ctx.fillRect(-20*ss,-17*ss,40*ss,6*ss);ctx.fillStyle='#d8a568';ctx.fillRect(6*ss,-2*ss,14*ss,5*ss)}else if(m.type==='ranged'){ctx.fillStyle='#42674d';ctx.beginPath();ctx.arc(0,0,10*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle=col;ctx.fillRect(-7*ss,-13*ss,14*ss,5*ss);ctx.strokeStyle='#ead2a4';ctx.lineWidth=3*ss;ctx.beginPath();ctx.arc(6*ss,0,8*ss,-1.1,1.1);ctx.stroke()}else{ctx.fillStyle='#526879';ctx.beginPath();ctx.arc(0,0,11*ss,0,Math.PI*2);ctx.fill();ctx.fillStyle=col;ctx.fillRect(-10*ss,-15*ss,20*ss,6*ss);ctx.fillStyle='#d2d8dc';ctx.fillRect(7*ss,-2*ss,10*ss,5*ss)}ctx.restore();drawHP(X-16*ss,Y-22*ss,32*ss,5,m.hp,m.maxHp,col)}
function drawMap(){drawMapStatic();drawBuildings();drawResourceCamps();drawBases();drawTowers();drawBosses()}
function drawMinimap(){mctx.clearRect(0,0,194,194);mctx.fillStyle='#173a26';mctx.fillRect(0,0,194,194);mctx.strokeStyle='#2f9bb0';mctx.lineWidth=13;mctx.beginPath();mctx.moveTo(8,188);mctx.quadraticCurveTo(85,100,188,5);mctx.stroke();for(const l of ['top','mid','bot']){mctx.strokeStyle='#73593f';mctx.lineWidth=3;mctx.beginPath();lanePts[l].forEach((p,i)=>{const x=p[0]/WORLD*194,y=p[1]/WORLD*194;i?mctx.lineTo(x,y):mctx.moveTo(x,y)});mctx.stroke()}for(const t of Object.values(state.towers)){mctx.fillStyle=t.team==='blue'?'#59adff':'#ff667d';mctx.fillRect(t.x/WORLD*194-2,t.y/WORLD*194-2,4,4)}for(const b of Object.values(state.bosses||{})){mctx.fillStyle='#ffc04f';mctx.beginPath();mctx.arc(b.x/WORLD*194,b.y/WORLD*194,4,0,Math.PI*2);mctx.fill()}for(const p of Object.values(render.players)){mctx.fillStyle=p.team==='blue'?'#66b7ff':'#ff6d82';mctx.beginPath();mctx.arc(p.tx/WORLD*194,p.ty/WORLD*194,4,0,Math.PI*2);mctx.fill()}}
function updateUI(){const me=render.players[meId];if(!me)return;hname.textContent=heroes[me.hero]?.[1]||me.hero;lv.textContent='Lv.'+me.level;gold.textContent=me.gold+' gold';xp.textContent='XP '+me.xp;pts.textContent='SP '+(me.skillPoints||0);hp.style.width=(100*me.hp/me.maxHp)+'%';mp.style.width=(100*me.mana/me.maxMana)+'%';document.querySelectorAll('.skill').forEach(b=>{const n=Number(b.dataset.s);const cd=Math.ceil((me.cd?.[n]||0)/1000);const level=me.skill?.[n]||0;const need={1:1,2:2,3:4,4:6}[n];b.querySelector('b').textContent=cd>0?cd:'';b.querySelector('.lv').textContent=level;b.classList.toggle('haspoints',!!(me.skillPoints>0 && me.level>=need && level<4))})}
function screenWorld(x,y){return{x:(x-W/2)/cam.z+cam.x,y:(y-H/2)/cam.z+cam.y}}
function findEnemy(x,y){const me=render.players[meId];if(!me)return null;let best=null,bd=58/cam.z;for(const p of Object.values(render.players)){if(p.id===meId||p.dead||p.team===me.team)continue;const d=Math.hypot(x-p.tx,y-p.ty);if(d<bd){bd=d;best=p}}return best}
function renderLoop(now){const dt=Math.min(.033,(now-last)/1000);last=now;const me=render.players[meId];if(me){cam.x+=(me.x-cam.x)*Math.min(1,dt*7);cam.y+=(me.y-cam.y)*Math.min(1,dt*7);cam.z+=(Math.max(.72,Math.min(1.06,Math.min(W/1200,H/800)))-cam.z)*dt*2}ctx.clearRect(0,0,W,H);drawMap();for(const m of Object.values(render.minions)){m.x+=(m.tx-m.x)*Math.min(1,dt*12);m.y+=(m.ty-m.y)*Math.min(1,dt*12);drawMinion(m)}for(const p of Object.values(render.players)){p.x+=(p.tx-p.x)*Math.min(1,dt*11);p.y+=(p.ty-p.y)*Math.min(1,dt*11);drawHero(p,p.id===meId)}drawParticles(dt);drawMinimap();updateUI();if(moveTarget&&me&&!mobile){const dx=moveTarget.x-me.x,dy=moveTarget.y-me.y;if(Math.hypot(dx,dy)<55)moveTarget=null;else if(now-lastMoveSend>70){lastMoveSend=now;const d=Math.hypot(dx,dy)||1;send({type:'move',x:dx/d,y:dy/d,dir:Math.atan2(dy,dx)})}}requestAnimationFrame(renderLoop)}
function keyboard(){if(menu.style.display!=='none'||mobile){requestAnimationFrame(keyboard);return}let x=0,y=0;if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;if(keys.has('KeyW')||keys.has('ArrowUp'))y--;if(keys.has('KeyS')||keys.has('ArrowDown'))y++;if(x||y){moveTarget=null;const d=Math.hypot(x,y);send({type:'move',x:x/d,y:y/d,dir:Math.atan2(y,x)})}requestAnimationFrame(keyboard)}
function fxSkill(n){const me=render.players[meId];if(me)addFX(me.tx,me.ty,'spell',me.team)}
c.addEventListener('pointerdown',e=>{if(menu.style.display!=='none'||mobile)return;e.preventDefault();const w=screenWorld(e.clientX,e.clientY),me=render.players[meId],en=findEnemy(w.x,w.y);if(en){send({type:'attack'});addFX(en.tx,en.ty,'hit',en.team)}else if(me){moveTarget=w;const dx=w.x-me.x,dy=w.y-me.y,d=Math.hypot(dx,dy)||1;send({type:'move',x:dx/d,y:dy/d,dir:Math.atan2(dy,dx)})}});
addEventListener('keydown',e=>{keys.add(e.code);if(e.repeat)return;if(e.code==='Space'){send({type:'attack'});return}const map={KeyQ:1,KeyW:2,KeyE:3,KeyR:4};if(map[e.code]){send({type:'skill',n:map[e.code]});fxSkill(map[e.code])}});addEventListener('keyup',e=>keys.delete(e.code));
const joy=document.getElementById('joy'),knob=document.getElementById('knob');function joyUpdate(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.31,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy)||1,k=Math.min(1,max/l),x=dx*k,y=dy*k;knob.style.transform=`translate(${x}px,${y}px)`;send({type:'move',x:x/max,y:y/max,dir:Math.atan2(y,x)})}joy.addEventListener('pointerdown',e=>{if(!mobile)return;joyId=e.pointerId;joy.setPointerCapture(joyId);joyUpdate(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyUpdate(e)});['pointerup','pointercancel'].forEach(type=>joy.addEventListener(type,e=>{if(e.pointerId===joyId){joyId=null;knob.style.transform='translate(0,0)';send({type:'move',x:0,y:0})}}));
document.getElementById('attack').addEventListener('pointerdown',e=>{e.preventDefault();send({type:'attack'});const me=render.players[meId];if(me)addFX(me.tx,me.ty,'hit',me.team)});
document.querySelectorAll('.skill').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();const n=Number(b.dataset.s);send({type:'skill',n});fxSkill(n)}));document.querySelectorAll('.skill .skillPlus').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();send({type:'levelSkill',n:Number(b.parentElement.dataset.s)})}));
document.getElementById('shopBtn').onclick=()=>shop.classList.toggle('open');document.getElementById('closeShop').onclick=()=>shop.classList.remove('open');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>send({type:'buy',item:b.dataset.buy}));
document.getElementById('play').onclick=()=>{menu.style.display='none';hud.style.display='block';connect()};requestAnimationFrame(renderLoop);requestAnimationFrame(keyboard);
})();
