const http=require('http');const fs=require('fs');const path=require('path');const {WebSocketServer,WebSocket}=require('ws');
const PORT=Number(process.env.PORT||10000),ROOT=__dirname,MAP=2800,MAX=64;const players=new Map();let nextId=1;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.ico':'image/x-icon'};
function cleanName(v,f){if(typeof v!=='string')return f;const x=v.replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,20);return x||f}
function color(v,f){return typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v)?v:f}
function num(v,min,max,f){return Number.isFinite(v)?Math.max(min,Math.min(max,v)):f}
function safe(url){let d;try{d=decodeURIComponent(url.split('?')[0]||'/')}catch{return null}if(d==='/')d='/index.html';const norm=path.normalize(d).replace(/^[/\\]+/,'');const full=path.resolve(ROOT,norm);return full===ROOT||full.startsWith(ROOT+path.sep)?full:null}
const server=http.createServer((req,res)=>{const p=(req.url||'/').split('?')[0];if(p==='/health'||p==='/healthz'){res.writeHead(200,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});return res.end(JSON.stringify({ok:true,online:players.size}))}const f=safe(p);if(!f)return res.writeHead(403).end('Forbidden');fs.stat(f,(e,s)=>{if(e||!s.isFile())return res.writeHead(404).end('Not found');fs.readFile(f,(er,b)=>{if(er)return res.writeHead(500).end('Internal error');res.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream','cache-control':path.basename(f)==='index.html'?'no-cache':'public,max-age=3600'});res.end(b)})})});
const wss=new WebSocketServer({server,maxPayload:16*1024});
function snap(){const out={};for(const [id,p] of players)out[id]={id,name:p.name,hero:p.hero,color:p.color,x:p.x,y:p.y,hp:p.hp,maxHp:p.maxHp,team:p.team};return JSON.stringify({type:'state',players:out,online:players.size,ts:Date.now()})}
function broadcast(){const m=snap();for(const p of players.values())if(p.ws.readyState===WebSocket.OPEN)p.ws.send(m)}
function safeSend(ws,obj){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(obj))}
wss.on('connection',(ws)=>{if(players.size>=MAX)return ws.close(1013,'full');const id=String(nextId++),team=players.size%2===0?'blue':'red';const p={ws,id,name:`Player_${id}`,hero:'warrior',color:team==='blue'?'#4ea6ff':'#ff6677',x:team==='blue'?330:2470,y:team==='blue'?2440:360,hp:700,maxHp:700,team,last:0,pong:Date.now()};players.set(id,p);safeSend(ws,{type:'welcome',id,team});broadcast();ws.on('pong',()=>p.pong=Date.now());ws.on('message',(raw)=>{const now=Date.now();if(now-p.last<35)return;p.last=now;let m;try{m=JSON.parse(raw.toString())}catch{return}if(!m||typeof m.type!=='string')return;if(m.type==='join'){p.name=cleanName(m.name,p.name);p.hero=cleanName(m.hero,'warrior').slice(0,30);p.color=color(m.color,p.color);broadcast()}else if(m.type==='state'){p.x=num(m.x,0,MAP,p.x);p.y=num(m.y,0,MAP,p.y);p.hp=num(m.hp,0,10000,p.hp);p.maxHp=num(m.maxHp,1,10000,p.maxHp);p.name=cleanName(m.name,p.name);p.hero=cleanName(m.hero,p.hero);p.color=color(m.color,p.color);broadcast()}else if(m.type==='action'){broadcast()}});const bye=()=>{if(players.delete(id))broadcast()};ws.on('close',bye);ws.on('error',bye)});
const hb=setInterval(()=>{const now=Date.now();for(const p of players.values()){if(now-p.pong>35000){try{p.ws.terminate()}catch{}continue}if(p.ws.readyState===WebSocket.OPEN)p.ws.ping()}},5000);
function stop(){clearInterval(hb);for(const p of players.values())try{p.ws.close(1001)}catch{}server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),4000)};process.on('SIGTERM',stop);process.on('SIGINT',stop);
server.listen(PORT,'0.0.0.0',()=>console.log(`MOBA Arena online on ${PORT}`));