
import { HEROES } from '../shared/heroes.js';
import * as map from '../shared/map.js';
const {MAP,BASES,LANES,FOREST,TOWERS,BUILDINGS,CAMPS,BOSSES,lanePoint,dist,inWater,forestBlocked}=map;

const TICK=50, MAX_PLAYERS=40;
const state={players:new Map(),minions:new Map(),towers:new Map(),camps:new Map(),bosses:new Map(),wave:0,nextPlayer:1,nextUnit:1,lastWave:0};
for(const t of TOWERS) state.towers.set(t.id,{...t,lastShot:0,targetId:null});
for(const c of CAMPS) state.camps.set(c.id,{...c,maxHp:c.kind==='ancient'?1100:c.kind==='large'?780:520,hp:c.kind==='ancient'?1100:c.kind==='large'?780:520,alive:true,respawnAt:0});
for(const b of BOSSES) state.bosses.set(b.id,{...b,maxHp:b.hp,hp:b.hp,alive:true,respawnAt:0,lastAttack:0,phase:1});

const ITEMS={boots:{cost:250,speed:35},blade:{cost:650,damage:26,crit:0.06},armor:{cost:550,armor:12},wand:{cost:700,maxMana:180,spellPower:24},orb:{cost:900,health:240,spellPower:35},scepter:{cost:1500,spellPower:65,ultPower:0.15}};
const SKILL_LEVELS=[0,1,2,4,6];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function norm(x,y){const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}}
function heroStats(p){const h=HEROES[p.hero]; return {...h, hp:h.hp+p.level*42+(p.items.health||0), mana:h.mana+p.level*20+(p.items.maxMana||0), speed:h.speed+(p.items.speed||0), damage:h.damage+p.level*4+(p.items.damage||0), armor:h.armor+(p.items.armor||0), spellPower:(p.items.spellPower||0)}}
function teamBase(team){return team==='blue'?BASES.blue:BASES.red}
function sanitizeName(n,id){return String(n||`Player_${id}`).replace(/[^\p{L}\p{N}_ -]/gu,'').trim().slice(0,18)||`Player_${id}`}

// --- Grid / navmesh ---
const NAV=new Uint8Array(MAP.cols*MAP.rows); for(let gy=0;gy<MAP.rows;gy++)for(let gx=0;gx<MAP.cols;gx++){const x=(gx+.5)*MAP.cell,y=(gy+.5)*MAP.cell;NAV[gy*MAP.cols+gx]=forestBlocked(x,y)?0:1}
function cell(x,y){return {x:clamp(Math.floor(x/MAP.cell),0,MAP.cols-1),y:clamp(Math.floor(y/MAP.cell),0,MAP.rows-1)}}
function walkable(gx,gy){return gx>=0&&gy>=0&&gx<MAP.cols&&gy<MAP.rows&&NAV[gy*MAP.cols+gx]===1}
function astar(sx,sy,gx,gy){sx=clamp(sx,0,MAP.cols-1);sy=clamp(sy,0,MAP.rows-1);gx=clamp(gx,0,MAP.cols-1);gy=clamp(gy,0,MAP.rows-1);const start=sy*MAP.cols+sx,goal=gy*MAP.cols+gx;const open=[start],came=new Int32Array(MAP.cols*MAP.rows);came.fill(-1);const g=new Float32Array(MAP.cols*MAP.rows);g.fill(1e9);g[start]=0;const f=new Float32Array(MAP.cols*MAP.rows);f.fill(1e9);f[start]=Math.hypot(gx-sx,gy-sy);const seen=new Uint8Array(MAP.cols*MAP.rows);let loops=0;
 while(open.length&&loops++<800){let best=0;for(let i=1;i<open.length;i++)if(f[open[i]]<f[open[best]])best=i;const cur=open.splice(best,1)[0];if(cur===goal){const path=[];let c=cur;while(c!==-1){path.push({x:(c%MAP.cols+.5)*MAP.cell,y:(Math.floor(c/MAP.cols)+.5)*MAP.cell});c=came[c]}return path.reverse()}seen[cur]=1;const cx=cur%MAP.cols,cy=Math.floor(cur/MAP.cols);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const nx=cx+dx,ny=cy+dy;if(!walkable(nx,ny))continue;const ni=ny*MAP.cols+nx;if(seen[ni])continue;const ng=g[cur]+Math.hypot(dx,dy);if(ng<g[ni]){came[ni]=cur;g[ni]=ng;f[ni]=ng+Math.hypot(gx-nx,gy-ny);if(!open.includes(ni))open.push(ni)}}}
 return [{x:(sx+.5)*MAP.cell,y:(sy+.5)*MAP.cell},{x:(gx+.5)*MAP.cell,y:(gy+.5)*MAP.cell}]
}
function ensurePath(u,x,y){const s=cell(u.x,u.y),g=cell(x,y);const key=`${s.x},${s.y}:${g.x},${g.y}`;if(u.pathKey!==key||!u.path||u.pathIdx>=u.path.length){u.pathKey=key;u.path=astar(s.x,s.y,g.x,g.y);u.pathIdx=1}}

function applyDamage(target,raw,source){if(!target||target.dead)return false;const armor=target.armor||0;const mult=100/(100+Math.max(-50,armor));let dmg=raw*mult;if(source&&source.items?.crit&&Math.random()<source.items.crit)dmg*=1.65;target.hp=Math.max(0,target.hp-dmg);target.lastAggro=source?.id||target.lastAggro;if(target.hp<=0)kill(target,source);return true}
function kill(target,source){if(target.type==='hero'){target.dead=true;target.respawnAt=Date.now()+Math.min(14000,7000+target.level*450);target.gold=Math.max(0,target.gold-100);target.inputX=target.inputY=0;target.targetId=null;award(source,180,260)} else if(target.type==='minion'){award(source,target.kind==='siege'?75:target.kind==='ranged'?42:34,target.kind==='siege'?80:45)} else if(target.type==='camp'){target.alive=false;target.respawnAt=Date.now()+target.respawn*1000;award(source,target.reward,target.xp)} else if(target.type==='boss'){target.alive=false;target.respawnAt=Date.now()+target.respawn*1000;award(source,target.reward,target.xp)} else if(target.type==='tower'){target.hp=0;award(source,220,220)} }
function award(p,gold,xp){if(!p||p.type!=='hero')return;p.gold+=gold;p.xp+=xp;while(p.xp>=p.level*220&&p.level<30){p.xp-=p.level*220;p.level++;p.skillPoints++;p.hp=Math.min(p.maxHp(),p.hp+80);p.mana=Math.min(p.maxMana(),p.mana+30)}}

function makePlayer(ws,id){const team=[...state.players.values()].filter(p=>p.team==='blue').length<=[...state.players.values()].filter(p=>p.team==='red').length?'blue':'red';const hero='guardian',h=HEROES[hero],b=teamBase(team);const p={type:'hero',id,ws,team,name:`Player_${id}`,hero,x:b.x,y:b.y,serverX:b.x,serverY:b.y,lastAck:0,seq:0,lastInput:{x:0,y:0},dir:0,targetId:null,dead:false,respawnAt:0,invulnerableUntil:Date.now()+2000,level:1,xp:0,gold:600,skillPoints:0,skills:[0,1,0,0,0],cooldowns:[0,0,0,0,0],attackCd:0,items:{speed:0,damage:0,armor:0,maxMana:0,health:0,spellPower:0,crit:0},inventory:[],path:null};p.maxHp=()=>heroStats(p).hp;p.maxMana=()=>heroStats(p).mana;p.hp=h.hp;p.mana=h.mana;return p}

function currentTarget(p){if(p.targetId){return state.players.get(p.targetId)||state.minions.get(p.targetId)||state.towers.get(p.targetId)||state.camps.get(p.targetId)||state.bosses.get(p.targetId)||null}return null}
function isEnemy(a,b){if(!a||!b)return false;if(b.type==='camp'||b.type==='boss')return true;return a.team&&b.team&&a.team!==b.team}
function acquire(p,range){let best=null,score=1e9;const candidates=[...state.players.values(),...state.minions.values(),...state.towers.values(),...state.bosses.values()];for(const q of candidates){if(q===p||q.hp<=0||q.dead||!isEnemy(p,q))continue;const d=dist(p,q);if(d>range)continue;let priority=q.type==='hero'?0:q.type==='tower'?1:q.type==='minion'?(q.kind==='siege'?2:3):4;const s=priority*10000+d;if(s<score){score=s;best=q}}return best}
function canCast(p,n){const req=SKILL_LEVELS[n]||99;return !p.dead&&p.skillPoints>=0&&p.skills[n]>=1&&p.level>=req&&p.cooldowns[n]<=0}
function cast(p,n,targetX,targetY,targetId){if(!canCast(p,n))return;const h=heroStats(p),now=Date.now();const costs=[0,70,95,125,180],cds=[0,5500,8500,10500,42000];if(p.mana<costs[n])return;p.mana-=costs[n];p.cooldowns[n]=cds[n];
 const target=targetId?(state.players.get(targetId)||state.minions.get(targetId)||null):null;
 if(n===1){const t=target||acquire(p,h.range+160);if(t)applyDamage(t,h.skills[0]+p.spellPower()+p.level*8,p)}
 else if(n===2){const amt=h.hp*.18+p.level*18;p.hp=Math.min(h.hp,p.hp+amt)}
 else if(n===3){const x=Number(targetX)||p.x,y=Number(targetY)||p.y;for(const q of [...state.players.values(),...state.minions.values()])if(isEnemy(p,q)&&dist({x,y},q)<260)applyDamage(q,h.skills[2]*1.05+p.spellPower()+p.level*10,p)}
 else {for(const q of [...state.players.values(),...state.minions.values()])if(isEnemy(p,q)&&!q.dead&&dist(p,q)<720)applyDamage(q,h.skills[3]+p.spellPower()*1.4+p.level*16,p);p.invulnerableUntil=now+700}
}
function spellPower(p){return heroStats(p).spellPower||0}

function buy(p,item){const it=ITEMS[item];if(!it||p.gold<it.cost||p.inventory.length>=6)return; p.gold-=it.cost;p.inventory.push(item);for(const k of ['speed','damage','armor','maxMana','health','spellPower','crit'])if(it[k])p.items[k]=(p.items[k]||0)+it[k]}

function spawnMinion(team,lane,kind,t){const id=`m${state.nextUnit++}`,p=lanePoint(lane,t,team==='blue');const stats=kind==='melee'?{hp:440,damage:28,range:150,speed:112,cd:1100}:kind==='ranged'?{hp:340,damage:30,range:290,speed:104,cd:1250}:{hp:780,damage:56,range:320,speed:82,cd:1200};state.minions.set(id,{type:'minion',id,team,lane,kind,x:p.x,y:p.y,hp:stats.hp,maxHp:stats.hp,armor:kind==='siege'?14:8,...stats,lastAttack:0,path:null,pathKey:'',pathIdx:0,targetId:null,lastSeen:0})}
function spawnWave(){const now=Date.now();if(now-state.lastWave<30000)return;state.lastWave=now;state.wave++;for(const team of ['blue','red'])for(const lane of ['top','mid','bot']){for(let i=0;i<3;i++)spawnMinion(team,lane,'melee',0.02+i*0.012);for(let i=0;i<2;i++)spawnMinion(team,lane,'ranged',0.07+i*0.012);if(state.wave%3===0)spawnMinion(team,lane,'siege',0.12)} }
function minionTarget(m){let best=null,bd=260;for(const p of state.players.values())if(p.team!==m.team&&!p.dead&&dist(m,p)<bd){bd=dist(m,p);best=p}for(const q of state.minions.values())if(q.team!==m.team&&q.lane===m.lane&&q.hp>0&&dist(m,q)<bd){bd=dist(m,q);best=q}for(const t of state.towers.values())if(t.team!==m.team&&t.hp>0&&t.lane===m.lane&&dist(m,t)<bd){bd=dist(m,t);best=t}return best}
function updateMinions(dt){const now=Date.now();for(const m of state.minions.values()){if(m.hp<=0)continue;const t=minionTarget(m);if(t){if(now-m.lastAttack>m.cd){m.lastAttack=now;applyDamage(t,m.damage,m)}}else{const goal=lanePoint(m.lane,Math.min(1.04,((m.t||0.02)+(m.speed*dt/1000)/4600)),m.team==='blue');m.t=(m.t||0.02)+(m.speed*dt/1000)/4600;ensurePath(m,goal.x,goal.y);const node=m.path?.[m.pathIdx]||goal;const d=norm(node.x-m.x,node.y-m.y);const step=m.speed*dt/1000;m.x+=d.x*step;m.y+=d.y*step;if(dist(m,node)<14)m.pathIdx++;if(m.t>1.02)m.hp=0}}
 for(const [id,m] of state.minions)if(m.hp<=0)state.minions.delete(id)}
function towerAcquire(t){let hero=null,heroD=1e9,minion=null,minD=1e9;for(const p of state.players.values())if(p.team!==t.team&&!p.dead&&dist(t,p)<t.range&&dist(t,p)<heroD){hero=p;heroD=dist(t,p)}for(const m of state.minions.values())if(m.team!==t.team&&m.hp>0&&dist(t,m)<t.range&&dist(t,m)<minD){minion=m;minD=dist(t,m)}return minion||hero}
function updateTowers(){const now=Date.now();for(const t of state.towers.values()){if(t.hp<=0)continue;const q=towerAcquire(t);if(q&&now-t.lastShot>900){t.lastShot=now;applyDamage(q,120+(t.tier*18),t)}}}
function updateCamps(){const now=Date.now();for(const c of state.camps.values())if(!c.alive&&now>=c.respawnAt){c.alive=true;c.hp=c.maxHp}for(const b of state.bosses.values()){if(!b.alive&&now>=b.respawnAt){b.alive=true;b.hp=b.maxHp;b.phase=1}}}
function bossUpdate(){const now=Date.now();for(const b of state.bosses.values()){if(!b.alive)continue;const hpRatio=b.hp/b.maxHp;b.phase=hpRatio<.33?3:hpRatio<.66?2:1;let target=null,bd=b.range;for(const p of state.players.values())if(!p.dead&&dist(b,p)<bd){bd=dist(b,p);target=p}if(target&&now-b.lastAttack>1100){b.lastAttack=now;applyDamage(target,b.damage*(b.phase===3?1.25:1),b);if(b.phase>=2){for(const q of state.players.values())if(q!==target&&dist(b,q)<250)applyDamage(q,b.damage*.35,b)}}}}
function heroUpdate(dt){const now=Date.now();for(const p of state.players.values()){if(p.dead){if(now>=p.respawnAt){const b=teamBase(p.team);p.x=b.x;p.y=b.y;p.dead=false;p.hp=heroStats(p).hp;p.mana=heroStats(p).mana;p.invulnerableUntil=now+2500}continue}const h=heroStats(p),inp=norm(p.lastInput.x,p.lastInput.y),slow=inWater(p.x,p.y)?.72:1;const speed=h.speed*slow;const nx=p.x+inp.x*speed*dt/1000,ny=p.y+inp.y*speed*dt/1000;const s=cell(p.x,p.y),g=cell(nx,ny);if(walkable(g.x,g.y)){p.x=clamp(nx,80,MAP.w-80);p.y=clamp(ny,80,MAP.h-80)}p.serverX=p.x;p.serverY=p.y;p.attackCd=Math.max(0,p.attackCd-dt);for(let i=1;i<=4;i++)p.cooldowns[i]=Math.max(0,p.cooldowns[i]-dt);p.mana=Math.min(h.mana,p.mana+11*dt/1000);if(p.targetId&&p.attackCd<=0){const t=currentTarget(p)||acquire(p,h.range+20);if(t&&isEnemy(p,t)&&dist(p,t)<=h.range+22){p.attackCd=h.attackCd*1000;applyDamage(t,h.damage,p)}else if(!t)p.targetId=null}for(const q of [...state.players.values(),...state.minions.values()]){if(q===p||!q.lastAggro)continue;if(q.lastAggro===p.id&&q.type==='minion'){} }if(p.hp<=0&&!p.dead)kill(p,p.lastAggro?state.players.get(p.lastAggro):null)}}
function campCombat(){const now=Date.now();for(const c of state.camps.values()){if(!c.alive)continue;for(const p of state.players.values()){if(p.dead||dist(p,c)>280)continue;if(p.attackCd<=0&&p.targetId===c.id){const h=heroStats(p);p.attackCd=h.attackCd*1000;applyDamage(c,h.damage,p)}if(dist(p,c)<220&&now-(c.lastAttack||0)>1400){c.lastAttack=now;applyDamage(p,c.kind==='ancient'?55:35,c)}}}}
function visibilityFor(p){const vis=new Set([p.id]);for(const q of state.players.values())if(q.team===p.team||dist(p,q)<900)vis.add(q.id);for(const q of state.minions.values())if(q.team===p.team||dist(p,q)<650)vis.add(q.id);for(const t of state.towers.values())if(t.team===p.team||dist(p,t)<700)vis.add(t.id);for(const c of state.camps.values())if(dist(p,c)<550)vis.add(c.id);for(const b of state.bosses.values())if(dist(p,b)<1000)vis.add(b.id);return vis}
function snapshot(p){const vis=visibilityFor(p);const pack=(obj)=>Object.fromEntries([...obj].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));const players=Object.fromEntries([...state.players].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));const towers=Object.fromEntries([...state.towers].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));const minions=Object.fromEntries([...state.minions].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));const camps=Object.fromEntries([...state.camps].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));const bosses=Object.fromEntries([...state.bosses].filter(([id])=>vis.has(id)).map(([id,v])=>[id,serialize(v)]));return {type:'state',serverTime:Date.now(),ack:p.seq,wave:state.wave,online:state.players.size,players,minions,towers,camps,bosses,buildings:BUILDINGS,map:{w:MAP.w,h:MAP.h},self:{x:p.x,y:p.y,hp:p.hp,mana:p.mana,dead:p.dead,gold:p.gold,xp:p.xp,level:p.level,skills:p.skills,skillPoints:p.skillPoints,cooldowns:p.cooldowns,attackCd:p.attackCd,inventory:p.inventory,items:p.items,seq:p.seq}}}
function serialize(o){return {...o,ws:undefined,path:undefined,lastInput:undefined,maxHp:typeof o.maxHp==='function'?o.maxHp():o.maxHp,maxMana:typeof o.maxMana==='function'?o.maxMana():o.maxMana}}
function validateMove(x,y){const v=Number(x),w=Number(y);return Number.isFinite(v)&&Number.isFinite(w)?{x:clamp(v,-1,1),y:clamp(w,-1,1)}:{x:0,y:0}}
function attach(ws){const id=`p${state.nextPlayer++}`;const p=makePlayer(ws,id);state.players.set(id,p);ws.send(JSON.stringify({type:'welcome',id,team:p.team,map:MAP}));ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='input'){p.seq=Number(m.seq)||p.seq;p.lastInput=validateMove(m.x,m.y);p.dir=Number(m.dir)||p.dir;if(m.attack)p.targetId=typeof m.targetId==='string'?m.targetId:null}else if(m.type==='join'){p.name=sanitizeName(m.name,id);if(HEROES[m.hero]){p.hero=m.hero;p.hp=HEROES[m.hero].hp;p.mana=HEROES[m.hero].mana}}else if(m.type==='skill'){cast(p,Number(m.n),m.x,m.y,m.targetId)}else if(m.type==='levelSkill'){const n=Number(m.n);if(n>=1&&n<=4&&p.skillPoints>0&&p.skills[n]<4&&p.level>=SKILL_LEVELS[p.skills[n]+1]){p.skills[n]++;p.skillPoints--}}else if(m.type==='buy')buy(p,String(m.item))});const drop=()=>{state.players.delete(id)};ws.on('close',drop);ws.on('error',drop);return p}
function cellWalk(x,y){return walkable(x,y)}
function tick(dt){spawnWave();heroUpdate(dt);updateMinions(dt);updateTowers();updateCamps();bossUpdate();campCombat()}
function publicMeta(){return {map:MAP,bases:BASES,lanes:LANES,forest:FOREST,water:map.WATER,towers:TOWERS,buildings:BUILDINGS,camps:CAMPS,bosses:BOSSES}}
export {state,attach,tick,snapshot,publicMeta,MAP,cellWalk,TICK};
