import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type User = { id:number; username:string; email:string; xp:number; role:string; rank:{name:string;xp:number} };
type Site = {id:string;title:string;url:string;icon:string;category:string};
type Tab = {id:string;title:string;url:string};
const roleLabel=(r:string)=>r==='admin'?'ADMIN':r==='assistant'?'HELPER':'USER';

function csrfToken(){return document.cookie.split('; ').find(x=>x.startsWith('od_csrf='))?.split('=')[1]||'';}
async function api(path:string, opts:RequestInit={}){
  const headers=new Headers(opts.headers||{});
  if(opts.body && !(opts.body instanceof FormData) && !headers.has('content-type')) headers.set('content-type','application/json');
  if(!['GET','HEAD','OPTIONS'].includes((opts.method||'GET').toUpperCase()) && !path.startsWith('/api/auth/')) headers.set('X-CSRF-Token', decodeURIComponent(csrfToken()));
  const r=await fetch(path,{credentials:'include',...opts,headers});
  if(!r.ok) throw new Error((await r.json().catch(()=>({error:r.statusText}))).error||'REQUEST_FAILED');
  return r.json();
}

function Auth({onLogin}:{onLogin:(u:User)=>void}){
  const [mode,setMode]=useState<'login'|'register'>('login'); const [login,setLogin]=useState(''); const [email,setEmail]=useState(''); const [pass,setPass]=useState(''); const [err,setErr]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setErr('');try{const data=await api('/api/auth/'+mode,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(mode==='login'?{login,password:pass}:{username:login,email,password:pass})});onLogin(data.user)}catch(e:any){setErr(e.message)}}
  return <div className="auth-shell"><div className="auth-card"><div className="brand">◈ OrbitDesk</div><p className="muted">Твой персональный рабочий браузер</p><div className="seg"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Вход</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Регистрация</button></div><form onSubmit={submit}>{<input value={login} onChange={e=>setLogin(e.target.value)} placeholder={mode==='login'?'Логин или email':'Логин'} required/>}{mode==='register'&&<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email" required/>}<input value={pass} onChange={e=>setPass(e.target.value)} placeholder="Пароль" type="password" minLength={10} required/><button className="primary wide">{mode==='login'?'Войти':'Создать аккаунт'}</button>{err&&<div className="error">{err}</div>}</form><small className="muted">Пароль: минимум 10 символов, цифра, A-Z и a-z.</small></div></div>
}

function App(){
 const [user,setUser]=useState<User|null>(null); const [sites,setSites]=useState<Site[]>([]); const [tabs,setTabs]=useState<Tab[]>([]); const [active,setActive]=useState('home'); const [query,setQuery]=useState(''); const [theme,setTheme]=useState('midnight'); const [accent,setAccent]=useState('#6ea8ff'); const [modal,setModal]=useState<string|null>(null); const [notice,setNotice]=useState(''); const [photoUrl,setPhotoUrl]=useState(''); const ws=useRef<WebSocket|null>(null); const [friends,setFriends]=useState<any[]>([]); const [selectedFriend,setSelectedFriend]=useState<any|null>(null); const [messages,setMessages]=useState<any[]>([]);
 useEffect(()=>{api('/api/me').then(setUser).catch(()=>{});},[]);
 useEffect(()=>{if(!user)return;api('/api/config').then(x=>setSites(x.sites));api('/api/settings').then(x=>{setTheme(x.theme);setAccent(x.accent)}).catch(()=>{});api('/api/friends').then(setFriends).catch(()=>{});ws.current=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.current.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='chat'){setMessages(m=>[...m,d.message]);}};return()=>ws.current?.close()},[user]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--accent',accent)},[theme,accent]);
 if(!user)return <Auth onLogin={setUser}/>;
 const openSite=(s:Site)=>{const id=crypto.randomUUID();setTabs(t=>[...t,{id,title:s.title,url:s.url}]);setActive(id)};
 const openUrl=()=>{if(!query.trim())return;let u=query.trim();if(!/^https?:\/\//i.test(u))u='https://'+u;openSite({id:'custom',title:u.replace(/^https?:\/\//,'').slice(0,30),url:u,icon:'🌐',category:'custom'})};
 async function saveSettings(next:any){await api('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(next)});setNotice('Сохранено');setTimeout(()=>setNotice(''),1500)}
 async function uploadPhoto(file:File){const fd=new FormData();fd.append('photo',file);const d=await fetch('/api/photos',{method:'POST',body:fd,credentials:'include'});if(!d.ok)throw new Error('UPLOAD_FAILED');const x=await d.json();setPhotoUrl(x.url);}
 function chatSend(text:string){if(!text||!selectedFriend||!ws.current)return;ws.current.send(JSON.stringify({type:'chat',to:selectedFriend.user_id,body:text}))}
 return <div className="app"><aside className="sidebar"><div className="brand small">◈ OrbitDesk</div><button className={active==='home'?'nav active':'nav'} onClick={()=>setActive('home')}>⌂ Главная</button><button className="nav" onClick={()=>setModal('sites')}>＋ Сайты</button><button className="nav" onClick={()=>setModal('tables')}>▦ Таблицы</button><button className="nav" onClick={()=>setModal('photos')}>◉ Фото</button><button className="nav" onClick={()=>setModal('chat')}>☏ Чат</button><button className="nav" onClick={()=>setModal('settings')}>⚙ Настройки</button>{user.role==='admin'&&<button className="nav admin" onClick={()=>setModal('admin')}>⚙ Админ</button>}<div className="sidebar-bottom"><div className="profile">{user.username}<span>{roleLabel(user.role)}</span></div><button className="ghost" onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()}}>Выйти</button></div></aside><main className="main"><div className="topbar"><div className="tabs"><button className={active==='home'?'tab active':'tab'} onClick={()=>setActive('home')}>Домой</button>{tabs.map(t=><button key={t.id} className={active===t.id?'tab active':'tab'} onClick={()=>setActive(t.id)}>{t.title}<span onClick={e=>{e.stopPropagation();setTabs(ts=>ts.filter(x=>x.id!==t.id));if(active===t.id)setActive('home')}}>×</span></button>)}</div><div className="top-actions"><span className="rank">{user.rank.name}</span><span className="xp">{user.xp} XP</span></div></div><div className="omnibar"><button className="ghost">←</button><button className="ghost">→</button><input value={active==='home'?query:(tabs.find(t=>t.id===active)?.url||'')} onChange={e=>active==='home'&&setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&active==='home'&&openUrl()} placeholder="Введите сайт или поисковый запрос..."/><button className="primary" onClick={active==='home'?openUrl:()=>{}}>{active==='home'?'Открыть':'↗'}</button></div><section className="content">{active==='home'?<Home sites={sites} onOpen={openSite} user={user}/>:<iframe className="webview" src={tabs.find(t=>t.id===active)?.url||'about:blank'} title="site" sandbox="allow-scripts allow-forms allow-popups allow-same-origin"/>}</section></main>{modal&&<Modal kind={modal} close={()=>setModal(null)} sites={sites} openSite={openSite} theme={theme} setTheme={(v)=>{setTheme(v);saveSettings({theme:v,accent})}} accent={accent} setAccent={(v)=>{setAccent(v);saveSettings({theme,accent:v})}} uploadPhoto={uploadPhoto} photoUrl={photoUrl} friends={friends} selectedFriend={selectedFriend} setSelectedFriend={setSelectedFriend} messages={messages} onSend={chatSend} setMessages={setMessages} user={user} notice={notice}/>}</div>
}

function Home({sites,onOpen,user}:{sites:Site[];onOpen:(s:Site)=>void;user:User}){return <div className="home"><div className="hero"><div><div className="eyebrow">PERSONAL WORKSPACE</div><h1>Привет, {user.username}.</h1><p>Сайты, таблицы, фото, друзья и быстрые команды — всё в одном месте.</p></div><div className="hero-card"><b>{user.rank.name}</b><span>{user.xp} XP</span></div></div><div className="quick"><h2>Доступные сайты</h2><div className="site-grid">{sites.map(s=><button key={s.id} className="site-card" onClick={()=>onOpen(s)}><span className="icon">{s.icon}</span><div><b>{s.title}</b><small>{s.url}</small></div></button>)}{!sites.length&&<div className="empty">Администратор ещё не добавил быстрые сайты для этой роли.</div>}</div></div><div className="info-grid"><div className="info-card"><b>Горячие клавиши</b><p>Сайты можно добавлять в вкладки и привязывать к клавишам в настройках.</p></div><div className="info-card"><b>Приватность</b><p>Секреты не хранятся в GitHub. Фото шифруются на сервере.</p></div><div className="info-card"><b>Роль</b><p>Текущий доступ: {roleLabel(user.role)}.</p></div></div></div>}

function Modal(p:any){const [text,setText]=useState('');return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&p.close()}><div className="modal"><div className="modal-head"><h3>{p.kind==='sites'?'Быстрые сайты':p.kind==='tables'?'Таблицы':p.kind==='photos'?'Фото':p.kind==='chat'?'Чат':p.kind==='admin'?'Администрирование':'Настройки'}</h3><button className="ghost" onClick={p.close}>×</button></div>{p.kind==='sites'&&<div className="modal-list">{p.sites.map((s:Site)=><button key={s.id} className="list-row" onClick={()=>{p.openSite(s);p.close()}}><span>{s.icon}</span><div><b>{s.title}</b><small>{s.url}</small></div><em>Открыть</em></button>)}</div>}{p.kind==='tables'&&<div className="table-demo"><div className="muted">Таблицы хранятся в PostgreSQL. Создание/редактирование доступно через API и может быть расширено под полноценный редактор.</div></div>}{p.kind==='photos'&&<div><label className="upload"><input type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={e=>e.target.files?.[0]&&p.uploadPhoto(e.target.files[0])}/>Выбрать фото</label>{p.photoUrl&&<img className="photo-preview" src={p.photoUrl}/>}</div>}{p.kind==='chat'&&<div className="chat"><div className="friend-list">{p.friends.map((f:any)=><button className={p.selectedFriend?.user_id===f.user_id?'active':''} key={f.user_id} onClick={async()=>{p.setSelectedFriend(f);try{const x=await api('/api/messages/'+f.user_id);p.setMessages?.(x)}catch{}}}>{f.username} · {f.rank?.name}</button>)}</div><div className="chat-main">{p.selectedFriend?<><div className="chat-messages">{p.messages.map((m:any,i:number)=><div key={i} className={m.sender_id===p.user.id?'mine':'theirs'}>{m.body}</div>)}</div><div className="chat-send"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){p.onSend(text);setText('')}}} placeholder="Сообщение..."/><button className="primary" onClick={()=>{p.onSend(text);setText('')}}>→</button></div></>:<div className="empty">Выбери друга.</div>}</div></div>}{p.kind==='admin'&&<div className="admin-panel"><div className="muted">Управление ролями доступно через защищённый API. Здесь можно разместить список пользователей и назначать user / assistant / admin.</div><pre>{JSON.stringify({current:p.user.role},null,2)}</pre></div>}{p.kind==='settings'&&<div className="settings"><label>Тема<select value={p.theme} onChange={e=>p.setTheme(e.target.value)}><option value="midnight">Midnight</option><option value="graphite">Graphite</option><option value="light">Light</option><option value="amoled">AMOLED</option></select></label><label>Accent<input value={p.accent} onChange={e=>p.setAccent(e.target.value)} /></label>{p.notice&&<div className="notice">{p.notice}</div>}</div>}</div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
