import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type User={id:number;username:string;email:string;xp:number;role:string;email_verified?:boolean;rank:{name:string;xp:number}};
type Site={id:string;title:string;url:string;icon:string;category:string;uses?:number};
type Tab={id:string;kind:'site'|'table'|'profile'|'settings'|'chat'|'admin'|'integrations'|'history';title:string;url?:string;site?:Site;tableId?:number|string};
type TableDoc={id:number;name:string;payload:{columns:string[];rows:string[][]};updated_at:string};
type Settings={theme:string;accent:string;compact:boolean;blur:number;sidebar:number;roundness:number;wallpaper:string;showClock:boolean;displayName:string;bio:string;avatarUrl:string;particlesEnabled:boolean;particleColor:string;particleDensity:number;particleMaxSize:number;particleSpeed:number};
const roleLabel=(r:string)=>r==='admin'?'ADMIN':r==='assistant'?'HELPER':'USER';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('od_csrf='))?.split('=')[1]||'';}
async function api(path:string,opts:RequestInit={}){const h=new Headers(opts.headers||{});if(opts.body&&!(opts.body instanceof FormData)&&!h.has('content-type'))h.set('content-type','application/json');if(!['GET','HEAD','OPTIONS'].includes((opts.method||'GET').toUpperCase())&&!path.startsWith('/api/auth/'))h.set('X-CSRF-Token',decodeURIComponent(csrf()));const r=await fetch(path,{credentials:'include',...opts,headers:h});const d=await r.json().catch(()=>({error:r.statusText}));if(!r.ok)throw new Error(d.error||r.statusText);return d;}

function Auth({onLogin}:{onLogin:(u:User)=>void}){
  const[mode,setMode]=useState<'login'|'register'>('login'),[login,setLogin]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[code,setCode]=useState(''),[pending,setPending]=useState(false),[err,setErr]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setErr('');try{
    if(pending){const d=await api('/api/auth/verify-code',{method:'POST',body:JSON.stringify({email,code})});setPending(false);setCode('');setErr('');onLogin(d.user);return;}
    const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(mode==='login'?{login,password:pass}:{username:login,email,password:pass})});
    if(mode==='register'){setPending(true);setErr('Код подтверждения отправлен на почту.');}else onLogin(d.user);
  }catch(e:any){const map:any={SMTP_NOT_CONFIGURED:'Почта временно не настроена на сервере. Администратор должен задать SMTP.',EMAIL_NOT_VERIFIED:'Сначала подтверди почту кодом из письма.',BAD_CODE:'Неверный 6-значный код.',CODE_EXPIRED:'Код истёк. Запроси новый.',TOO_MANY_ATTEMPTS:'Слишком много неверных попыток. Запроси новый код позже.',ALREADY_EXISTS:'Такой основной логин или email уже зарегистрирован.',INVALID_CREDENTIALS:'Неверный логин/email или пароль.',BAD_USERNAME:'Основной логин: 3–32 символа, только A–Z, a–z, 0–9 и _.',BAD_EMAIL:'Проверь адрес электронной почты.',WEAK_PASSWORD:'Пароль должен быть от 10 символов и содержать заглавную, строчную букву и цифру.',REGISTER_FAILED:'Не удалось создать аккаунт. Проверь данные и попробуй снова.',LOGIN_FAILED:'Не удалось выполнить вход. Попробуй ещё раз.'};setErr(map[e.message]||e.message);}}
  async function resend(){try{await api('/api/auth/resend-code',{method:'POST',body:JSON.stringify({email})});setErr('Новый код отправлен на почту.');}catch(e:any){const map:any={SMTP_NOT_CONFIGURED:'Почта временно не настроена на сервере.',USER_NOT_FOUND:'Аккаунт с таким email не найден.',BAD_EMAIL:'Проверь email.'};setErr(map[e.message]||e.message)}}
  return <div className="auth-shell"><div className="auth-card"><div className="brand">◈ OrbitDesk</div>
    <p className="muted">Личный браузер, таблицы, сайты и друзья.</p>
    {!pending&&<div className="seg"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Вход</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Регистрация</button></div>}
    <form onSubmit={submit}>
      {pending?<><input value={email} readOnly/><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-значный код" inputMode="numeric" required/><button className="primary wide">Подтвердить почту</button><button type="button" className="ghost wide" onClick={resend}>Отправить код ещё раз</button></>:<><input value={login} onChange={e=>setLogin(e.target.value)} placeholder={mode==='login'?'Логин или email':'Основной логин'} required/>{mode==='register'&&<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email" required/>}<input value={pass} onChange={e=>setPass(e.target.value)} placeholder="Пароль" type="password" minLength={10} required/><button className="primary wide">{mode==='login'?'Войти':'Создать аккаунт'}</button></>}
      {err&&<div className="error">{err}</div>}
    </form>
    <small className="muted">{pending?'Код действует 15 минут.':'Пароль: 10+ символов, A-Z, a-z, цифра.'}</small>
  </div></div>;
}

function Particles({settings}:{settings:Settings}){
  const seed=useMemo(()=>Array.from({length:72},(_,i)=>({i,x:(i*37)%100,y:(i*61)%100,d:2+(i%5),delay:(i%10)*.4,dur:5+(i%8),size:2+(i%Math.max(2,settings.particleMaxSize))})),[settings.particleMaxSize]);
  if(!settings.particlesEnabled)return null;
  return <div className="particle-layer" aria-hidden>{seed.slice(0,settings.particleDensity).map(p=><span key={p.i} style={{left:`${p.x}%`,top:`${p.y}%`,width:p.size,height:p.size,background:settings.particleColor,animationDelay:`${p.delay}s`,animationDuration:`${Math.max(3,p.dur/(settings.particleSpeed||.45))}s`}}/>)}</div>;
}

function App(){
 const[user,setUser]=useState<User|null>(null),[sites,setSites]=useState<Site[]>([]),[bookmarks,setBookmarks]=useState<Site[]>([]),[frequent,setFrequent]=useState<Site[]>([]),[suggestions,setSuggestions]=useState<Site[]>([]),[tabs,setTabs]=useState<Tab[]>([]),[active,setActive]=useState('home'),[query,setQuery]=useState('');
 const[settings,setSettings]=useState<Settings>({theme:'midnight',accent:'#68a1ff',compact:false,blur:16,sidebar:270,roundness:14,wallpaper:'',showClock:true,displayName:'',bio:'',avatarUrl:'',particlesEnabled:false,particleColor:'#8ab4ff',particleDensity:24,particleMaxSize:4,particleSpeed:.45});
 const[tables,setTables]=useState<TableDoc[]>([]),[friends,setFriends]=useState<any[]>([]),[notice,setNotice]=useState(''),ws=useRef<WebSocket|null>(null),suggestTimer=useRef<any>(null);
 useEffect(()=>{api('/api/me').then(setUser).catch(()=>setUser(null))},[]);
 useEffect(()=>{if(!user)return;(async()=>{try{const[cfg,s,tb,fs,bm]=await Promise.all([api('/api/config'),api('/api/settings'),api('/api/tables'),api('/api/friends'),api('/api/bookmarks')]);setSites(cfg.sites||[]);setSettings(x=>({...x,...s}));setTables(tb||[]);setFriends(fs||[]);setBookmarks((bm||[]).map((x:any)=>({id:`b-${x.id}`,title:x.title,url:x.url,icon:x.icon,category:x.category})));}catch{} })();connect();return()=>{try{ws.current?.close()}catch{}};},[user]);
 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.style.setProperty('--accent',settings.accent);document.documentElement.style.setProperty('--radius',settings.roundness+'px');document.documentElement.style.setProperty('--sidebar',settings.sidebar+'px');document.documentElement.style.setProperty('--blur',settings.blur+'px');if(settings.wallpaper)document.documentElement.style.setProperty('--wallpaper',`url(${settings.wallpaper})`);else document.documentElement.style.removeProperty('--wallpaper');},[settings]);
 useEffect(()=>{if(!user)return;if(suggestTimer.current)clearTimeout(suggestTimer.current);suggestTimer.current=setTimeout(async()=>{try{const d=await api('/api/sites/suggest?q='+encodeURIComponent(query));setSuggestions(d.suggestions||[]);const h=await api('/api/history');const counts:any={};for(const x of h){counts[x.url]=(counts[x.url]||0)+1;}setFrequent(Object.entries(counts).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6).map(([url,uses]:any)=>({id:'freq-'+url,title:String(url).replace(/^https?:\/\//,'').slice(0,34),url,icon:'↻',category:'frequent',uses})));}catch{}},220);return()=>clearTimeout(suggestTimer.current)},[query,user]);
 function connect(){try{const w=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.current=w;w.onclose=()=>setTimeout(connect,2500);}catch{}}
 async function saveSettings(next:Partial<Settings>){const merged={...settings,...next};setSettings(merged);await api('/api/settings',{method:'PUT',body:JSON.stringify(merged)});toast('Сохранено')}
 function toast(x:string){setNotice(x);setTimeout(()=>setNotice(''),1500)}
 async function persist(next:Tab[]){setTabs(next);await api('/api/tabs',{method:'PUT',body:JSON.stringify({tabs:next.filter(t=>t.kind==='site'&&t.url).map((t,i)=>({title:t.title,url:t.url,position:i}))})}).catch(()=>{})}
 function openSite(site:Site,url=site.url){const id=crypto.randomUUID();persist([...tabs,{id,kind:'site',title:site.title,url,site}]);setActive(id);api('/api/history',{method:'POST',body:JSON.stringify({url,title:site.title})}).catch(()=>{})}
 async function addSite(){let u=query.trim();if(!u)return;if(!/^https?:\/\//i.test(u))u='https://'+u;const title=u.replace(/^https?:\/\//,'').replace(/\/$/,'').slice(0,42)||'Сайт';try{await api('/api/sites/add',{method:'POST',body:JSON.stringify({title,url:u})});const d=await api('/api/sites/suggest?q='+encodeURIComponent(query));setSuggestions(d.suggestions||[]);openSite({id:'custom',title,url:u,icon:'🌐',category:'custom'},u);setQuery('');toast('Сайт добавлен')}catch(e:any){toast(e.message)}}
 function internal(kind:Tab['kind'],title:string,extra:Partial<Tab>={}){const id=`${kind}-${Date.now()}`;setTabs(x=>[...x,{id,kind,title,...extra}]);setActive(id)}
 function closeTab(id:string){const nt=tabs.filter(t=>t.id!==id);if(active===id)setActive('home');persist(nt)}
 async function logout(){await api('/api/auth/logout',{method:'POST'});location.reload()}
 const resolveInput=(raw:string)=>{const v=raw.trim();if(/^https?:\/\//i.test(v))return v;if(/^[^\s]+\.[^\s]+$/.test(v))return 'https://'+v;return 'https://www.google.com/search?q='+encodeURIComponent(v)};
 const activeTab=tabs.find(t=>t.id===active);
 if(!user)return <Auth onLogin={setUser}/>;
 return <div className="app"><Particles settings={settings}/><aside className="sidebar"><div className="brand small">◈ OrbitDesk</div>
   <button className={active==='home'?'nav active':'nav'} onClick={()=>setActive('home')}>⌂ Главная</button><button className="nav" onClick={()=>internal('table','Таблицы')}>▦ Таблицы</button><button className="nav" onClick={()=>internal('integrations','Google / Подключения')}>🔗 Подключения</button><button className="nav" onClick={()=>internal('profile','Профиль')}>◉ Профиль</button><button className="nav" onClick={()=>internal('chat','Чат')}>☏ Чат</button><button className="nav" onClick={()=>internal('history','История')}>🕘 История</button><button className="nav" onClick={()=>internal('settings','Настройки')}>⚙ Настройки</button>{user.role==='admin'&&<button className="nav admin" onClick={()=>internal('admin','Админ')}>🛡 Админ</button>}
   <div className="sidebar-bottom"><div className="profile"><div className="avatar">{settings.avatarUrl?<img src={settings.avatarUrl} alt="avatar"/>:(settings.displayName||user.username)[0]}</div><div><b>{settings.displayName||user.username}</b><span>{roleLabel(user.role)}</span></div></div><button className="ghost" onClick={logout}>Выйти</button></div>
 </aside><main className="main"><div className="topbar"><div className="tabs"><button className={active==='home'?'tab active':'tab'} onClick={()=>setActive('home')}>Домой</button>{tabs.map(t=><button key={t.id} className={active===t.id?'tab active':'tab'} onClick={()=>setActive(t.id)}>{t.title}<span onClick={e=>{e.stopPropagation();closeTab(t.id)}}>×</span></button>)}</div><div className="top-actions"><span className="rank">{user.rank.name}</span><span className="xp">{user.xp} XP</span></div></div>
 <div className="omnibar"><button className="ghost" onClick={()=>window.history.back()}>←</button><button className="ghost" onClick={()=>window.history.forward()}>→</button><input value={activeTab?.kind==='site'?(activeTab.url||''):active==='home'?query:''} onChange={e=>activeTab?.kind==='site'?setTabs(ts=>ts.map(t=>t.id===activeTab.id?{...t,url:e.target.value}:t)):active==='home'&&setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&active==='home'){const u=resolveInput(query);openSite({id:'custom',title:query||'Сайт',url:u,icon:'🌐',category:'custom'},u);}}} placeholder="Введите сайт или название…"/><button className="primary" onClick={active==='home'?()=>{const u=resolveInput(query);openSite({id:'custom',title:query||'Сайт',url:u,icon:'🌐',category:'custom'},u)}:()=>setActive(active)}>Открыть</button></div>
 {active==='home'&&query&&<div className="suggest-box">{suggestions.map(s=><button key={s.id} onClick={()=>{openSite(s);setQuery('')}}><span>{s.icon}</span><b>{s.title}</b><small>{s.url}</small>{s.uses? <em>{s.uses}×</em>:null}</button>)}<button className="suggest-add" onClick={addSite}>＋ Добавить «{query}» как свой сайт</button></div>}
 {!user.email_verified&&<div className="email-banner">Почта не подтверждена. <button onClick={()=>api('/api/email/resend',{method:'POST'}).then(()=>toast('Новый код отправлен')).catch((e:any)=>toast(e.message))}>Отправить код</button></div>}
 <section className="content">{active==='home'?<Home user={user} settings={settings} sites={sites} bookmarks={bookmarks} frequent={frequent} open={openSite} table={()=>internal('table','Таблицы')}/>:activeTab?.kind==='site'?<SiteView tab={activeTab}/>:activeTab?.kind==='table'?<TablesView tables={tables} setTables={setTables} openIntegrations={()=>internal('integrations','Google / Подключения')}/>:activeTab?.kind==='profile'?<ProfileView user={user} settings={settings} save={saveSettings}/>:activeTab?.kind==='settings'?<SettingsView settings={settings} save={saveSettings}/>:activeTab?.kind==='chat'?<ChatView friends={friends} ws={ws}/>:activeTab?.kind==='integrations'?<IntegrationsView/>:activeTab?.kind==='history'?<HistoryView/>:activeTab?.kind==='admin'?<AdminView/>:<div className="empty">Вкладка не найдена.</div>}</section>{notice&&<div className="toast">{notice}</div>}</main></div>
}

function Home({user,settings,sites,bookmarks,frequent,open,table}:{user:User;settings:Settings;sites:Site[];bookmarks:Site[];frequent:Site[];open:(s:Site)=>void;table:()=>void}){
 const quick=bookmarks.slice(0,8);
 return <div className="home"><div className="hero"><div><div className="eyebrow">PERSONAL WORKSPACE</div><h1>Привет, {settings.displayName||user.username}.</h1><p>{settings.bio||'Открывай сайты, таблицы и сервисы прямо в вкладках OrbitDesk.'}</p></div><div className="hero-card"><b>{user.rank.name}</b><span>{user.xp} XP</span></div></div>
   <div className="quick"><div className="section-head"><h2>Мои быстрые сайты</h2><span className="muted">Добавляй сам</span></div><div className="site-grid">{quick.map(s=><button key={s.id} className="site-card" onClick={()=>open(s)}><span className="icon">{s.icon}</span><div><b>{s.title}</b><small>{s.url}</small></div></button>)}{!quick.length&&<div className="info-card">Начни вводить сайт сверху — OrbitDesk предложит популярные варианты и позволит добавить свой.</div>}</div></div>
   {frequent.length>0&&<div className="quick"><div className="section-head"><h2>Часто используешь</h2><span className="muted">Запоминается автоматически</span></div><div className="site-grid">{frequent.map(s=><button key={s.id} className="site-card" onClick={()=>open(s)}><span className="icon">{s.icon}</span><div><b>{s.title}</b><small>{s.uses} открытий</small></div></button>)}</div></div>}
   <div className="info-grid"><button className="info-card action-card" onClick={()=>open({id:'google-docs',title:'Google Docs',url:'https://docs.google.com/document/',icon:'📝',category:'productivity'})}><b>Google Docs</b><p>Быстрый доступ к Google Документам.</p></button><button className="info-card action-card" onClick={table}><b>Таблицы</b><p>Локальные таблицы + Google Sheets.</p></button><div className="info-card"><b>Профиль</b><p>Основной логин неизменяемый, визуальное имя и внешний вид — настраиваются.</p></div><div className="info-card"><b>{user.email_verified?'Email подтверждён':'Email не подтверждён'}</b><p>{user.email}</p></div></div>
 </div>
}

function SiteView({tab}:{tab:Tab}){const[loading,setLoading]=useState(true);useEffect(()=>setLoading(true),[tab.url]);return <div className="site-workspace"><div className="site-toolbar"><div><b>{tab.title}</b><span className="muted"> {loading?'загрузка…':'готово'}</span></div><div className="site-tools"><button className="ghost" onClick={()=>setLoading(true)}>↻</button><button className="ghost" onClick={()=>window.open(tab.url,'_blank','noopener,noreferrer')}>↗ Отдельно</button></div></div><div className="site-layout"><div className="site-frame-wrap"><iframe key={tab.url} className="webview" src={tab.url||'about:blank'} title={tab.title} onLoad={()=>setLoading(false)} referrerPolicy="strict-origin-when-cross-origin"/></div><aside className="site-panel"><b>OrbitDesk Browser</b><p className="muted smalltxt">Сайт открыт внутри вкладки. Популярность и частота использования сохраняются в истории.</p><button className="ghost" onClick={()=>navigator.clipboard?.writeText(tab.url||'')}>Копировать URL</button></aside></div></div>}

function TablesView({tables,setTables,openIntegrations}:{tables:TableDoc[];setTables:React.Dispatch<React.SetStateAction<TableDoc[]>>;openIntegrations:()=>void}){
 const[selected,setSelected]=useState<number|string|null>(tables[0]?.id??null),[saving,setSaving]=useState(''),[ai,setAi]=useState('');const t=tables.find(x=>String(x.id)===String(selected));useEffect(()=>{if(selected==null&&tables[0])setSelected(tables[0].id)},[tables,selected]);
 async function create(){const x=await api('/api/tables',{method:'POST',body:JSON.stringify({name:'Новая таблица',payload:{columns:['A','B','C'],rows:[['','',''],['','',''],['','','']]}})});setTables(a=>[x,...a]);setSelected(x.id);}
 function update(mut:(x:TableDoc)=>void){if(!t)return;setTables(a=>a.map(x=>String(x.id)===String(t.id)?(()=>{const c={...x,payload:{columns:[...x.payload.columns],rows:x.payload.rows.map(r=>[...r])}};mut(c);return c})():x));setSaving('Изменено…');}
 useEffect(()=>{if(!t||saving!=='Изменено…')return;const id=setTimeout(async()=>{const fresh=tables.find(x=>String(x.id)===String(t.id));if(!fresh)return;const s=await api('/api/tables/'+fresh.id,{method:'PUT',body:JSON.stringify({name:fresh.name,payload:fresh.payload})});setTables(a=>a.map(x=>String(x.id)===String(fresh.id)?s:x));setSaving('Сохранено');setTimeout(()=>setSaving(''),1000)},700);return()=>clearTimeout(id)},[tables,saving,t]);
 function addRow(){update(x=>x.payload.rows.push(new Array(x.payload.columns.length).fill('')))} function addCol(){update(x=>{x.payload.columns.push(String.fromCharCode(65+x.payload.columns.length));x.payload.rows.forEach(r=>r.push(''))})}
 function aiHelp(){if(!t)return;const heads=t.payload.columns.join(', ');const sums=t.payload.columns.filter(x=>/(цена|сумм|amount|price|count|кол)/i.test(x));setAi(sums.length?`ИИ-подсказка: для столбцов ${sums.join(', ')} можно добавить формулу SUM. Пример: =SUM(${sums[0]}2:${sums[0]}100). Заголовки таблицы: ${heads}`:`ИИ-подсказка: вижу столбцы ${heads}. Добавь числовые поля, чтобы можно было строить суммы, средние и итоговые строки.`)}
 return <div className="table-workspace"><div className="table-sidebar"><div className="section-head"><b>Таблицы</b><button className="primary mini" onClick={create}>＋</button></div><button className="ghost wide" onClick={openIntegrations}>Google Sheets →</button>{tables.map(x=><button key={x.id} className={String(x.id)===String(selected)?'table-item active':'table-item'} onClick={()=>setSelected(x.id)}>{x.name}<span>{new Date(x.updated_at).toLocaleTimeString()}</span></button>)}</div><div className="table-editor">{t?<><div className="table-head"><input value={t.name} onChange={e=>update(x=>x.name=e.target.value)}/><div className="row-actions"><span className="muted">{saving||`Обновлено ${new Date(t.updated_at).toLocaleString()}`}</span><button className="ghost" onClick={addRow}>+ строка</button><button className="ghost" onClick={addCol}>+ столбец</button><button className="ghost" onClick={aiHelp}>✨ AI</button></div></div>{ai&&<div className="info-card ai-card">{ai}</div>}<table><thead><tr>{t.payload.columns.map((c,i)=><th key={i}><input value={c} onChange={e=>update(x=>x.payload.columns[i]=e.target.value)}/></th>)}</tr></thead><tbody>{t.payload.rows.map((r,ri)=><tr key={ri}>{r.map((c,ci)=><td key={ci}><input value={c} onChange={e=>update(x=>x.payload.rows[ri][ci]=e.target.value)}/></td>)}</tr>)}</tbody></table></>:<div className="empty big">Создай таблицу кнопкой ＋</div>}</div></div>
}

function ProfileView({user,settings,save}:{user:User;settings:Settings;save:(x:Partial<Settings>)=>Promise<void>}){const[l,setL]=useState(settings);useEffect(()=>setL(settings),[settings]);return <div className="settings-page"><div className="profile-card"><div className="big-avatar">{l.avatarUrl?<img src={l.avatarUrl} alt="avatar"/>:(l.displayName||user.username)[0]}</div><h1>{l.displayName||user.username}</h1><div className="muted">Основной логин: {user.username} (изменить нельзя)</div><span className="rank">{roleLabel(user.role)} · {user.rank.name}</span></div><div className="settings-grid"><label>Визуальное имя<input value={l.displayName} onChange={e=>setL({...l,displayName:e.target.value.slice(0,40)})}/></label><label>Фото / аватар URL<input value={l.avatarUrl} onChange={e=>setL({...l,avatarUrl:e.target.value.slice(0,2000000)})} placeholder="Вставь URL или data:image..."/></label><label>Описание<textarea value={l.bio} onChange={e=>setL({...l,bio:e.target.value.slice(0,240)})}/></label><div className="info-card">Роль: <b>{roleLabel(user.role)}</b><br/>Email: <b>{user.email}</b></div><button className="primary" onClick={()=>save(l)}>Сохранить профиль</button></div></div>}

function SettingsView({settings,save}:{settings:Settings;save:(x:Partial<Settings>)=>Promise<void>}){const[s,setS]=useState(settings);return <div className="settings-page"><h1>Настройки</h1><div className="settings-grid"><label>Тема<select value={s.theme} onChange={e=>setS({...s,theme:e.target.value})}><option value="midnight">Midnight</option><option value="graphite">Graphite</option><option value="light">Light</option><option value="amoled">AMOLED</option><option value="ocean">Ocean</option><option value="sunset">Sunset</option></select></label><label>Основной цвет<input type="color" value={s.accent} onChange={e=>setS({...s,accent:e.target.value})}/></label><label>Обои URL<input value={s.wallpaper} onChange={e=>setS({...s,wallpaper:e.target.value})}/></label><label>Sidebar<input type="range" min="220" max="360" value={s.sidebar} onChange={e=>setS({...s,sidebar:Number(e.target.value)})}/></label><label>Blur<input type="range" min="0" max="24" value={s.blur} onChange={e=>setS({...s,blur:Number(e.target.value)})}/></label><label>Партиклы <select value={s.particlesEnabled?'on':'off'} onChange={e=>setS({...s,particlesEnabled:e.target.value==='on'})}><option value="off">Выкл. (по умолчанию)</option><option value="on">Вкл.</option></select></label><label>Цвет партиклов<input type="color" value={s.particleColor} onChange={e=>setS({...s,particleColor:e.target.value})}/></label><label>Количество<input type="range" min="8" max="72" value={s.particleDensity} onChange={e=>setS({...s,particleDensity:Number(e.target.value)})}/></label><label>Макс. размер<input type="range" min="2" max="6" value={s.particleMaxSize} onChange={e=>setS({...s,particleMaxSize:Number(e.target.value)})}/></label><label>Скорость<input type="range" min=".1" max="1.5" step=".05" value={s.particleSpeed} onChange={e=>setS({...s,particleSpeed:Number(e.target.value)})}/></label><button className="primary" onClick={()=>save(s)}>Сохранить</button></div></div>}

function ChatView({friends,ws}:{friends:any[];ws:React.MutableRefObject<WebSocket|null>}){const[f,setF]=useState<any>(friends[0]||null),[m,setM]=useState<any[]>([]),[text,setText]=useState('');useEffect(()=>{if(f)api('/api/messages/'+f.user_id).then(setM).catch(()=>{})},[f]);function send(){if(!f||!text.trim()||!ws.current)return;ws.current.send(JSON.stringify({type:'chat',to:f.user_id,body:text.trim()}));setText('')}return <div className="chat-page"><aside className="chat-list">{friends.map(x=><button className={f?.user_id===x.user_id?'active':''} key={x.user_id} onClick={()=>setF(x)}>{x.username}<small>{x.rank.name}</small></button>)}</aside><section className="chat-main">{f?<><div className="chat-header">{f.username}</div><div className="messages">{m.map((x:any)=><div className="message" key={x.id}><b>{x.sender_name}</b><span>{x.body}</span></div>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Сообщение…"/><button className="primary">Отправить</button></form></>:<div className="empty big">Добавь друга</div>}</section></div>}

function IntegrationsView(){const[connected,setConnected]=useState<any[]>([]),[sheets,setSheets]=useState<any[]>([]),[sel,setSel]=useState<any|null>(null),[data,setData]=useState<any[][]>([]),[range,setRange]=useState(''),[error,setError]=useState(''),[creating,setCreating]=useState(false);useEffect(()=>{api('/api/integrations').then(setConnected).catch(()=>{})},[]);const googleConnected=connected.some(x=>x.provider==='google');async function connectGoogle(){window.location.href='/api/integrations/google/start'}async function list(){setError('');try{setSheets(await api('/api/google/sheets'))}catch(e:any){setError(e.message)}}async function create(){const title=prompt('Название новой Google-таблицы','Новая таблица');if(!title)return;try{setCreating(true);const x=await api('/api/google/sheets',{method:'POST',body:JSON.stringify({title})});await list();window.open(x.url,'_blank','noopener,noreferrer')}catch(e:any){setError(e.message)}finally{setCreating(false)}}async function openSheet(x:any){const d=await api('/api/google/sheets/'+x.id);setSel(x);setRange(d.range);setData(d.values)}async function save(){if(!sel)return;await api('/api/google/sheets/'+sel.id,{method:'PUT',body:JSON.stringify({range,values:data})})}function cell(r:number,c:number,v:string){setData(a=>{const b=a.map(x=>[...x]);while(!b[r])b.push([]);b[r][c]=v;return b})}return <div className="settings-page"><h1>Google Sheets</h1><div className="info-card"><b>{googleConnected?'Google подключён':'Нужен вход в Google'}</b><p className="muted">Таблицы открываются через официальный OAuth и редактируются после подключения.</p>{!googleConnected?<button className="primary" onClick={connectGoogle}>Войти через Google</button>:<><button className="primary" onClick={list}>Загрузить мои таблицы</button><button className="ghost" onClick={create} disabled={creating}>＋ Создать таблицу</button></>}</div>{error&&<div className="error">{error}</div>}<div className="site-grid" style={{marginTop:16}}>{sheets.map(x=><button className="site-card" key={x.id} onClick={()=>openSheet(x)}><span className="icon">📊</span><div><b>{x.name}</b><small>{x.modifiedTime||''}</small></div></button>)}</div>{sel&&<div className="info-card" style={{marginTop:18}}><div className="section-head"><b>{sel.name}</b><div className="row-actions"><button className="ghost" onClick={()=>window.open(sel.webViewLink||('https://docs.google.com/spreadsheets/d/'+sel.id),'_blank','noopener,noreferrer')}>↗ Полный Google Sheets</button><button className="primary" onClick={save}>Сохранить в Google</button></div></div><input className="omnibar" value={range} onChange={e=>setRange(e.target.value)}/><div style={{overflow:'auto'}}><table><tbody>{data.map((r,ri)=><tr key={ri}>{Array.from({length:Math.max(r.length,8)}).map((_,ci)=><td key={ci} style={{border:'1px solid var(--border)'}}><input value={r[ci]||''} onChange={e=>cell(ri,ci,e.target.value)} /></td>)}</tr>)}</tbody></table></div></div>}</div>}

function HistoryView(){const[h,setH]=useState<any[]>([]);useEffect(()=>{api('/api/history').then(setH).catch(()=>{})},[]);return <div className="settings-page"><h1>История посещений</h1>{h.map(x=><div className="info-card" key={x.id} style={{marginBottom:8}}><b>{x.title||x.url}</b><div className="muted">{new Date(x.visited_at).toLocaleString()}</div><small>{x.url}</small></div>)}{!h.length&&<div className="empty">История пуста.</div>}</div>}
function AdminView(){const[tab,setTab]=useState<'users'|'history'|'audit'>('users'),[users,setUsers]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);useEffect(()=>{api('/api/admin/users').then(setUsers).catch(()=>{})},[]);useEffect(()=>{if(tab==='history')api('/api/admin/history').then(setHistory).catch(()=>{});if(tab==='audit')api('/api/admin/audit').then(setAudit).catch(()=>{})},[tab]);async function role(id:number,r:string){const u=await api('/api/admin/users/'+id+'/role',{method:'PUT',body:JSON.stringify({role:r})});setUsers(x=>x.map(a=>a.id===id?u:a))}return <div className="settings-page"><h1>Админ-панель</h1><div className="seg"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Пользователи</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>История</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>Журнал</button></div>{tab==='users'&&<div className="admin-table">{users.map(u=><div className="admin-row" key={u.id}><b>{u.username}</b><span>{u.email}</span><select value={u.role} onChange={e=>role(u.id,e.target.value)}><option value="user">USER</option><option value="assistant">HELPER</option><option value="admin">ADMIN</option></select><span>{u.rank.name}</span></div>)}</div>}{tab==='history'&&history.map(x=><div className="info-card" key={x.id} style={{marginBottom:8}}><b>{x.username} — {x.title||'Сайт'}</b><div>{x.url}</div><small>{new Date(x.visited_at).toLocaleString()}</small></div>)}{tab==='audit'&&audit.map(x=><div className="info-card" key={x.id} style={{marginBottom:8}}><b>{x.username||'system'} — {x.action}</b><div className="muted">{JSON.stringify(x.metadata)}</div><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div>}

createRoot(document.getElementById('root')!).render(<App/>);
